#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sun Nov 09 10:11:06 2008

import wx

# begin wxGlade: extracode
# end wxGlade



class frame_mainFrame_parent(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frame_mainFrame_parent.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.window_1 = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_1_pane_2 = wx.Panel(self.window_1, -1)
        self.window_2 = wx.SplitterWindow(self.window_1_pane_2, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_2_pane_1 = wx.Panel(self.window_2, -1)
        self.window_1_pane_1 = wx.Panel(self.window_1, -1)
        self.tree_ctrl_1 = wx.TreeCtrl(self.window_1_pane_1, -1, style=wx.TR_HAS_BUTTONS|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.panel_1 = wx.Panel(self.window_1_pane_1, -1)
        self.gDrawPanel = wx.Panel(self.window_2_pane_1, -1)
        self.window_2_pane_2 = wx.Panel(self.window_2, -1)
        
        # Menu Bar
        self.mainFrame_menubar = wx.MenuBar()
        self.SetMenuBar(self.mainFrame_menubar)
        # Menu Bar end
        self.mainFrame_statusbar = self.CreateStatusBar(1, 0)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frame_mainFrame_parent.__set_properties
        self.SetTitle("frame_1")
        self.mainFrame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        mainFrame_statusbar_fields = ["mainFrame_statusbar"]
        for i in range(len(mainFrame_statusbar_fields)):
            self.mainFrame_statusbar.SetStatusText(mainFrame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frame_mainFrame_parent.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        genomePanelSizer = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.tree_ctrl_1, 3, wx.EXPAND, 0)
        sizer_3.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.window_1_pane_1.SetSizer(sizer_3)
        genomePanelSizer.Add(self.gDrawPanel, 2, wx.EXPAND, 0)
        self.window_2_pane_1.SetSizer(genomePanelSizer)
        self.window_2.SplitHorizontally(self.window_2_pane_1, self.window_2_pane_2)
        sizer_2.Add(self.window_2, 1, wx.EXPAND, 0)
        self.window_1_pane_2.SetSizer(sizer_2)
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)
        sizer_1.Add(self.window_1, 2, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class frame_mainFrame_parent


class frame_mainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class frame_mainFrame


if __name__ == "__main__":
    chipFishApp = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    mainFrame_parent = frame_mainFrame(None, -1, "")
    chipFishApp.SetTopWindow(mainFrame_parent)
    mainFrame_parent.Show()
    chipFishApp.MainLoop()
