#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sun Mar 15 15:47:21 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class frame_mainFrame_parent(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frame_mainFrame_parent.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.window_1 = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_1_pane_2 = wx.Panel(self.window_1, -1)
        self.window_2 = wx.SplitterWindow(self.window_1_pane_2, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.panel_2 = wx.Panel(self.window_2, -1)
        self.viewControlsPanel = wx.Panel(self.panel_2, -1)
        self.panel_3 = wx.Panel(self.viewControlsPanel, -1)
        self.window_2_pane_1 = wx.Panel(self.window_2, -1)
        self.sizer_5_staticbox = wx.StaticBox(self.viewControlsPanel, -1, "Genomic Location")
        self.window_1_pane_1 = wx.Panel(self.window_1, -1)
        
        # Menu Bar
        self.mainFrame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.mainFrame_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        self.mainFrame_menubar.Append(wxglade_tmp_menu, "Edit")
        wxglade_tmp_menu = wx.Menu()
        self.mainFrame_menubar.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.mainFrame_menubar)
        # Menu Bar end
        self.mainFrame_statusbar = self.CreateStatusBar(1, 0)
        self.tree_ctrl_1 = wx.TreeCtrl(self.window_1_pane_1, -1, style=wx.TR_HAS_BUTTONS|wx.TR_NO_LINES|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.panel_1 = wx.Panel(self.window_1_pane_1, -1)
        self.gDrawPanel = wx.Panel(self.window_2_pane_1, -1, style=wx.TAB_TRAVERSAL|wx.FULL_REPAINT_ON_RESIZE)
        self.butBigLeft = wx.Button(self.viewControlsPanel, -1, "<<")
        self.butLeft = wx.Button(self.viewControlsPanel, -1, "<")
        self.textGoToLoc = wx.TextCtrl(self.panel_3, -1, "")
        self.butJumpTo = wx.Button(self.panel_3, -1, "Go to")
        self.butRight = wx.Button(self.viewControlsPanel, -1, ">")
        self.butBigRight = wx.Button(self.viewControlsPanel, -1, ">>")
        self.butZoomIn = wx.Button(self.viewControlsPanel, -1, "Zoom In")
        self.button_5 = wx.Button(self.viewControlsPanel, -1, "Zoom Out")
        self.panel_9 = wx.Panel(self.panel_2, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnBigViewLeft, self.butBigLeft)
        self.Bind(wx.EVT_BUTTON, self.OnViewLeft, self.butLeft)
        self.Bind(wx.EVT_TEXT, self.OnGotoLocationEdit, self.textGoToLoc)
        self.Bind(wx.EVT_BUTTON, self.OnJumpToGenomicLoc, self.butJumpTo)
        self.Bind(wx.EVT_BUTTON, self.OnViewRight, self.butRight)
        self.Bind(wx.EVT_BUTTON, self.OnViewBigRight, self.butBigRight)
        self.Bind(wx.EVT_BUTTON, self.OnButZoomIn, self.butZoomIn)
        self.Bind(wx.EVT_BUTTON, self.OnButZoomOut, self.button_5)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frame_mainFrame_parent.__set_properties
        self.SetTitle("chpfish 1 - oAxiom")
        self.mainFrame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        mainFrame_statusbar_fields = ["mainFrame_statusbar"]
        for i in range(len(mainFrame_statusbar_fields)):
            self.mainFrame_statusbar.SetStatusText(mainFrame_statusbar_fields[i], i)
        self.butBigLeft.SetToolTipString("Move view more to the left")
        self.butLeft.SetToolTipString("Move View Left")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frame_mainFrame_parent.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        gDrawPanelSizer = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.tree_ctrl_1, 3, wx.EXPAND, 0)
        sizer_3.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.window_1_pane_1.SetSizer(sizer_3)
        gDrawPanelSizer.Add(self.gDrawPanel, 7, wx.ALL|wx.EXPAND, 2)
        self.window_2_pane_1.SetSizer(gDrawPanelSizer)
        sizer_5.Add(self.butBigLeft, 0, wx.EXPAND, 0)
        sizer_5.Add(self.butLeft, 0, wx.EXPAND, 0)
        sizer_6.Add(self.textGoToLoc, 2, wx.EXPAND, 0)
        sizer_6.Add(self.butJumpTo, 0, wx.EXPAND, 0)
        self.panel_3.SetSizer(sizer_6)
        sizer_5.Add(self.panel_3, 1, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        sizer_5.Add(self.butRight, 0, wx.EXPAND, 0)
        sizer_5.Add(self.butBigRight, 0, wx.EXPAND, 0)
        sizer_5.Add(self.butZoomIn, 0, 0, 0)
        sizer_5.Add(self.button_5, 0, 0, 0)
        self.viewControlsPanel.SetSizer(sizer_5)
        sizer_4.Add(self.viewControlsPanel, 1, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 2)
        sizer_4.Add(self.panel_9, 3, wx.EXPAND, 0)
        self.panel_2.SetSizer(sizer_4)
        self.window_2.SplitHorizontally(self.window_2_pane_1, self.panel_2)
        sizer_2.Add(self.window_2, 1, wx.EXPAND, 0)
        self.window_1_pane_2.SetSizer(sizer_2)
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)
        sizer_1.Add(self.window_1, 2, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnBigViewLeft(self, event): # wxGlade: frame_mainFrame_parent.<event_handler>
        print("Event handler `OnBigViewLeft' not implemented!")
        event.Skip()

    def OnViewLeft(self, event): # wxGlade: frame_mainFrame_parent.<event_handler>
        print("Event handler `OnViewLeft' not implemented!")
        event.Skip()

    def OnGotoLocationEdit(self, event): # wxGlade: frame_mainFrame_parent.<event_handler>
        print("Event handler `OnGotoLocationEdit' not implemented!")
        event.Skip()

    def OnJumpToGenomicLoc(self, event): # wxGlade: frame_mainFrame_parent.<event_handler>
        print("Event handler `OnJumpToGenomicLoc' not implemented!")
        event.Skip()

    def OnViewRight(self, event): # wxGlade: frame_mainFrame_parent.<event_handler>
        print("Event handler `OnViewRight' not implemented!")
        event.Skip()

    def OnViewBigRight(self, event): # wxGlade: frame_mainFrame_parent.<event_handler>
        print("Event handler `OnViewBigRight' not implemented!")
        event.Skip()

    def OnButZoomIn(self, event): # wxGlade: frame_mainFrame_parent.<event_handler>
        print("Event handler `OnButZoomIn' not implemented!")
        event.Skip()

    def OnButZoomOut(self, event): # wxGlade: frame_mainFrame_parent.<event_handler>
        print("Event handler `OnButZoomOut' not implemented!")
        event.Skip()

# end of class frame_mainFrame_parent


if __name__ == "__main__":
    chipFishApp = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    mainFrame = frame_mainFrame_parent(None, -1, "")
    chipFishApp.SetTopWindow(mainFrame)
    mainFrame.Show()
    chipFishApp.MainLoop()
